# Generated by Django 5.0.4 on 2024-05-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_data',
        ),
    ]
